# Generated by Django 5.0.14 on 2025-09-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin_wheel', '0001_initial'),
    ]

    operations = [
    ]
